uploads = []
generated = []

[[outputs]]
id = "fGSjwJ7grQI_UkEZBRMfh"
uri = "file://buzpos-export.zip"
type = "unspecified"
title = "BUZ POS — Export Package"

[[outputs]]
id = "DiSs893yvfjzQS1iYYSay"
uri = "file://holla-export.zip"
type = "unspecified"
title = "HOLLA — Full Project Export"
